name: obsastro
channels:
  - default
dependencies:
  - python=3.8
  - sphinx
  - pip
  - pandas
  - matplotlib
  - scipy
  - tqdm
  - pip:
    - jupyter-book
    - jupyterlab
    - astropy
    - ipywidgets
    - reproject
    - photutils
    - cmasher